package com.muxxu.fever.fevermap.events {	import com.muxxu.fever.fevermap.vo.AppMessage;
	import flash.events.Event;	import flash.geom.Rectangle;	/**	 * Event fired by the <code>DataManagerEvent</code> singleton.	 * 	 * @author  Francois	 */	public class DataManagerEvent extends Event {				public static const NEED_APP_UPDATE:String			= "needApplicationUpdate";		public static const SHOW_APP_MESSAGE:String			= "showAppMessage";				public static const LOAD_REVISIONS_COMPLETE:String	= "loadRevisionsComplete";		public static const LOAD_REVISIONS_ERROR:String		= "loadRevisionsError";				public static const LOAD_TRACKING_COMPLETE:String	= "loadTrackingComplete";		public static const LOAD_TRACKING_ERROR:String		= "loadTrackingError";				public static const LOAD_AREA_COMPLETE:String		= "loadAreaComplete";		public static const LOAD_AREA_ERROR:String			= "loadAreaError";		public static const CENTER_MAP_ON_POUSTY:String			= "centerMapOn";				public static const UPDATE_MAP:String				= "updateMap";		public static const OPEN_ZONE:String				= "openMapZone";				public static const ADD_AREA_COMPLETE:String		= "addAreaComplete";		public static const ADD_AREA_ERROR:String			= "addAreaError";				public static const LOGOUT_COMPLETE:String			= "logoutComplete";				public static const LOGIN_COMPLETE:String			= "loginComplete";		public static const LOGIN_ERROR:String				= "loginError";				public static const UPDATE_POS_COMPLETE:String		= "updatePosComplete";		public static const UPDATE_POS_ERROR:String			= "updatePosError";				public static const GET_USERS_ON_COMPLETE:String	= "getUsersOnComplete";		public static const GET_USERS_ON_ERROR:String		= "getUsersOnError";				public static const ADD_MESSAGE_COMPLETE:String		= "addMessageComplete";		public static const ADD_MESSAGE_ERROR:String		= "addMessageError";				public static const REPORT_MESSAGE_ERROR:String		= "reportMessageError";				public static const PATH_FINDER_PATH_FOUND:String	= "pathFound";		public static const PATH_FINDER_NO_PATH_FOUND:String= "noPathFound";				public static const LOAD_MESSAGE_COMPLETE:String	= "loadMessageComplete";		public static const LOAD_MESSAGE_ERROR:String		= "loadMessageError";				public static const DATA_DOWNLOAD_COMPLETE:String	= "dataDownloadComplete";		public static const DATA_DOWNLOAD_ERROR:String		= "dataDownloadError";		public static const DATA_UPLOAD_COMPLETE:String		= "dataUploadComplete";		public static const DATA_UPLOAD_ERROR:String		= "dataUploadError";				public static const LOCK:String						= "lock";		public static const UNLOCK:String					= "unlock";				private var _resultCode:int;
		private var _area:Rectangle;
		private var _items:*;
		private var _message:AppMessage;						/* *********** *		 * CONSTRUCTOR *		 * *********** */		/**		 * Creates an instance of <code>DataManagerEvent</code>.		 */
		public function DataManagerEvent(type:String, resultCode:int = 0, area:Rectangle = null, items:* = null, message:AppMessage = null, bubbles:Boolean = false, cancelable:Boolean = false) {
			_message = message;
			_items = items;			_area = area;			_resultCode = resultCode;			super(type, bubbles, cancelable);		}						/* ***************** *		 * GETTERS / SETTERS *		 * ***************** */		/**		 * Gets the result code.		 */		public function get resultCode():int {			return _resultCode;		}				/**		 * Gets the area concerned by the loading.		 */		public function get area():Rectangle {			return _area;		}				/**		 * Gets the items to add.		 */		public function get items():* {			return _items;		}		/**		 * Gets the global message to display.		 */		public function get message():AppMessage {			return _message;		}		/* ****** *		 * PUBLIC *		 * ****** */		/**		 * Makes a clone of the event object.		 */		override public function clone():Event {
			return new DataManagerEvent(type, resultCode, area, items, message, bubbles, cancelable);
		}						/* ******* *		 * PRIVATE *		 * ******* */	}}